# Project: calculator
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = C:/Users/hp/Desktop/Calculator/Calculator/Calculation.o C:/Users/hp/Desktop/Calculator/Calculator/Scan.o C:/Users/hp/Desktop/Calculator/Calculator/main.o C:/Users/hp/Desktop/Calculator/Calculator/Print.o
LINKOBJ  = C:/Users/hp/Desktop/Calculator/Calculator/Calculation.o C:/Users/hp/Desktop/Calculator/Calculator/Scan.o C:/Users/hp/Desktop/Calculator/Calculator/main.o C:/Users/hp/Desktop/Calculator/Calculator/Print.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = calculator.exe
CXXFLAGS = $(CXXINCS) -g3 -g3
CFLAGS   = $(INCS) -g3 -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

C:/Users/hp/Desktop/Calculator/Calculator/Calculation.o: C:/Users/hp/Desktop/Calculator/Calculator/Calculation.cpp
	$(CPP) -c C:/Users/hp/Desktop/Calculator/Calculator/Calculation.cpp -o C:/Users/hp/Desktop/Calculator/Calculator/Calculation.o $(CXXFLAGS)

C:/Users/hp/Desktop/Calculator/Calculator/Scan.o: C:/Users/hp/Desktop/Calculator/Calculator/Scan.cpp
	$(CPP) -c C:/Users/hp/Desktop/Calculator/Calculator/Scan.cpp -o C:/Users/hp/Desktop/Calculator/Calculator/Scan.o $(CXXFLAGS)

C:/Users/hp/Desktop/Calculator/Calculator/main.o: C:/Users/hp/Desktop/Calculator/Calculator/main.cpp
	$(CPP) -c C:/Users/hp/Desktop/Calculator/Calculator/main.cpp -o C:/Users/hp/Desktop/Calculator/Calculator/main.o $(CXXFLAGS)

C:/Users/hp/Desktop/Calculator/Calculator/Print.o: C:/Users/hp/Desktop/Calculator/Calculator/Print.cpp
	$(CPP) -c C:/Users/hp/Desktop/Calculator/Calculator/Print.cpp -o C:/Users/hp/Desktop/Calculator/Calculator/Print.o $(CXXFLAGS)
